apiVersion: v1
kind: Service
metadata:
  name: qotd
spec:
  type: LoadBalancer
  selector:
    app: qotd
  ports:
  # QOTD (quote of the day port is 17)
  - name: qotd
    protocol: TCP
    port: 17
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd
spec:
  selector:
    matchLabels:
      app: qotd
  replicas: 1
  template:
    metadata:
      labels:
        app: qotd
    spec:
      containers:
      - name: qotd
        image: logstoneducation/qotd:0.0.1-vulnerability
        ports:
        - containerPort: 8080
